repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0  # Use the ref you want to point at
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-added-large-files
        args: ["--maxkb=1000"]
    -   id: check-ast
    # -   id: double-quote-string-fixer
    -   id: fix-encoding-pragma

-   repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.10.0  # Use the ref you want to point at
    hooks:
    -   id: python-use-type-annotations

-   repo: https://github.com/asottile/reorder_python_imports
    rev: v3.9.0
    hooks:
    -   id: reorder-python-imports

-   repo: https://github.com/pycqa/pydocstyle
    rev: 6.3.0  # pick a git hash / tag to point to
    hooks:
    -   id: pydocstyle

-   repo: https://github.com/psf/black
    rev: 23.3.0  # pick a git hash / tag to point to
    hooks:
    -   id: black
